### ISSUE TITLE
Outsource general algorithms

### ISSUE THREAD

**Issue by snowiow** [snowiow/SIFT#10]
Every Method which isn't a direct step of SIFT should be located into another file.

**Comment by Dgame** [comment]
Why are you writing in english, friendo?

**Comment by snowiow** [comment]
because it's no country for old man and not kein land für alte leute

**Comment by Dgame** [comment]
Oh, that makes sense, indeed.

**Comment by snowiow** [comment]
resolved 4ce561d2c05328830eaf393140ed902e485cb7d1
